### ISSUE TITLE
Error en "cc:start"

### ISSUE THREAD

**Issue by edgargs** [worldsibu/convector-example-drug-supply-chain#10]
Tengo este error al ejecutar el comando:
npm run cc:start 1.0

![captura de pantalla de 2018-09-18 10-14-00](https://user-images.githubusercontent.com/11461983/45697977-99515700-bb2c-11e8-9225-42c0079cad73.png)

**Comment by walmon** [comment]
Después de agregar unas mejoras a Convector este ejemplo quedó un poco atrás.

El fix ha quedado aplicado en (leve cambio en el README.md):

https://github.com/worldsibu/convector-example-drug-supply-chain/commit/84c50051ccc48abd432f6900091f529ed3157cef
